### ISSUE TITLE
Can't training using metadata. ValueError: stof

### ISSUE THREAD

**Issue by ThiagoBGL** [lsw9021/MASS#28]
I didn't use a virtualenv, but all requirement wers installed. Cmake install. But when try to start a traning this error shows up

python3 main.py -d ../data/metadata.txt
HumanTraceback (most recent call last):
  File "main.py", line 391, in <module>
    ppo = PPO(args.meta)
  File "main.py", line 65, in __init__
    self.env = EnvManager(meta_file,self.num_slaves)
ValueError: stof

**Comment by ThiagoBGL** [comment]
THe problem is result of import pymss
from pymss import EnvManager
"Unsolved reference"
How to recognize the file pymss.so???

**Comment by pumpudopoulus** [comment]
Have you found a solution?, I've seen on [another threat](https://github.com/lsw9021/MASS/issues/9) that during the execution of 'make -j8', the following appears: "[ 91%] Built target pymss" which indicates the pymss module comes from DART, but I don't know what I missed during the installation of DART.

**Comment by lsw9021** [comment]
The problem comes when c++ code couldn't link successfully. 

1. run render code and if it did successfully, then the problem is related to python, and boost python.
2. If not, then the problem is related to the DART, tinyxml, and etc.  

Check and please let me know.

**Comment by pumpudopoulus** [comment]
I've ran the render code from the MASS-master directory and the python directory, and the terminal gives this: 

`pumpudopoulus@LAPTOP-J8J0NMME:/mnt/c/users/jalta/desktop/mass-master$ cd python
pumpudopoulus@LAPTOP-J8J0NMME:/mnt/c/users/jalta/desktop/mass-master/python$ source env/bin/activate
(env) pumpudopoulus@LAPTOP-J8J0NMME:/mnt/c/users/jalta/desktop/mass-master/python$ ./render/render ../data/metadata.txt
-bash: ./render/render: No such file or directory
(env) pumpudopoulus@LAPTOP-J8J0NMME:/mnt/c/users/jalta/desktop/mass-master/python$ cd ,,
-bash: cd: ,,: No such file or directory
(env) pumpudopoulus@LAPTOP-J8J0NMME:/mnt/c/users/jalta/desktop/mass-master/python$ cd ..
(env) pumpudopoulus@LAPTOP-J8J0NMME:/mnt/c/users/jalta/desktop/mass-master$ ./render/render ../data/metadata.txt
-bash: ./render/render: No such file or directory`

**Comment by lsw9021** [comment]
You have to run ./render/render code in the build directory.

**Comment by noshaba** [comment]
Hi, I have the same problem. The render code works but I don't know what the problem with my python would be, or how to even dig deeper what may cause the problem... The error doesn't really give any clue.

**Comment by omerkayan** [comment]
Hi all. I have the same problem with noshaba. Render works. But I do not know the problem about python or boost. Could someone please help me ?
